{{- if eq (toString .Values.deploymentMode) "Deployment" }}
{{- $fullName := include "kubedeploy.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubedeploy.fullname" . }}
  labels:
    {{- include "kubedeploy.labels" . | nindent 4 }}
spec:
  {{- if not (or .Values.autoscaling.enabled .Values.keda.enabled ) }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubedeploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.configMapHash }}
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.configMapHash }}
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
      {{- end }}
      {{- end }}
      labels:
        {{- include "kubedeploy.selectorLabels" . | nindent 8 }}
    {{- include "kubedeploy.specSection" . | nindent 4 }}
{{- end }}
