{{- if eq (toString .Values.deploymentMode) "Job" }}
{{- $fullName := include "kubedeploy.fullname" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubedeploy.fullname" . }}
  labels:
    {{- include "kubedeploy.labels" . | nindent 4 }}
spec:
  {{- with .Values.jobspec.backoffLimit }}
  backoffLimit: {{ . }}
  {{- end }}
  {{- with .Values.jobspec.parallelism }}
  parallelism: {{ . }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubedeploy.selectorLabels" . | nindent 8 }}
    {{- include "kubedeploy.specSection" . | nindent 4 }}
{{- end }}
