{{- if eq (toString .Values.deploymentMode) "Statefulset" }}
{{- $fullName := include "kubedeploy.fullname" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kubedeploy.fullname" . }}
  labels:
    {{- include "kubedeploy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubedeploy.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "kubedeploy.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubedeploy.selectorLabels" . | nindent 8 }}
    {{- include "kubedeploy.specSection" . | nindent 4 }}
  {{- if and (.Values.persistency.enabled) (eq (toString .Values.deploymentMode) "Statefulset") }}
  volumeClaimTemplates:
    - metadata:
        name: {{ $fullName }}
      spec:
        accessModes:
        {{- range .Values.persistency.accessModes }}
          - {{ . }}
        {{- end }}
        storageClassName: {{ .Values.persistency.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.persistency.capacity.storage }}
  {{- end }}
{{- end }}
