---
name: Dev release

on:
  push:
    branches:
      - main
    paths:
      - kubedeploy/**
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  HELM_VERSION: "3.12.3"

jobs:

  tests:
    uses: ./.github/workflows/tests.yaml

  chart-release:
    runs-on: ubuntu-latest
    needs: tests
    steps:

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Install Helm S3 plugin
        run: helm plugin install https://github.com/hypnoglow/helm-s3.git

      - name: Add release repo
        run: |
          helm repo add sysbee-release s3://${{ secrets.S3_BUCKET }}/release/sysbee
          helm repo update

      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish the release chart
        run: |
          helm package kubedeploy
          helm s3 push --force --relative *.tgz sysbee-release
