---
name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  HELM_VERSION: "3.12.3"

jobs:

  tests:
    uses: ./.github/workflows/tests.yaml

  chart-release:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: write
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Install Helm S3 plugin
        run: helm plugin install https://github.com/hypnoglow/helm-s3.git

      - name: Add release repo
        run: |
          helm repo add sysbee s3://${{ secrets.S3_BUCKET }}/stable/sysbee
          helm repo update

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build chart artifacts
        run: helm package kubedeploy

      - name: Publish in chart repository
        run: helm s3 push --relative *.tgz sysbee

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            *.tgz
